# docs: https://alacritty.org/config-alacritty.html
# key bindings: https://alacritty.org/config-alacritty-bindings.html

[general]
# https://alacritty.org/config-alacritty.html#general
live_config_reload = true

[env]
# https://alacritty.org/config-alacritty.html#env
# Add your env vars
# MY_ENV = "value"
TERM = "xterm-256color"

[window]
# https://alacritty.org/config-alacritty.html#window
opacity = 0.9
#dynamic_title = false
padding.x = 1
padding.y = 1
decorations = "None"
decorations_theme_variant = "None" # "Dark" | "Light"
dimensions = { columns = 0, lines = 0 }
startup_mode = "Maximized"
option_as_alt = "OnlyLeft" # "OnlyRight" | "Both" | "None"
# dynamic_padding = true

[font]
# https://alacritty.org/config-alacritty.html#font
size = 13.0
normal.family = "JetBrainsMonoNL Nerd Font Mono"
bold.family = "JetBrainsMonoNL Nerd Font Mono"
italic.family = "JetBrainsMonoNL Nerd Font Mono"
bold_italic.family = "JetBrainsMonoNL Nerd Font Mono"

[scrolling]
# https://alacritty.org/config-alacritty.html#scrolling
history = 10000

[colors]
# https://alacritty.org/config-alacritty.html#colors
# Default colors
  primary.background = '0x1e2127'
  primary.foreground = '0xabb2bf'

    # Bright and dim foreground colors
    #
    # The dimmed foreground color is calculated automatically if it is not present.
    # If the bright foreground color is not set, or `draw_bold_text_with_bright_colors`
    # is `false`, the normal foreground color will be used.
    #dim_foreground: '0x9a9a9a'
   primary.bright_foreground = '0xe6efff'

  # Cursor colors
  #
  # Colors which should be used to draw the terminal cursor. If these are unset,
  # the cursor color will be the inverse of the cell color.
  #cursor:
  #  text: '0x000000'
  #  cursor: '0xffffff'

  # Normal colors
  normal.black = '0x1e2127'
  normal.red = '0xe06c75'
  normal.green = '0x98c379'
  normal.yellow = '0xd19a66'
  normal.blue = '0x61afef'
  normal.magenta = '0xc678dd'
  normal.cyan = '0x56b6c2'
  normal.white = '0x828791'

  # Bright colors
  bright.black =   '0x5c6370'
  bright.red =     '0xe06c75'
  bright.green =   '0x98c379'
  bright.yellow =  '0xd19a66'
  bright.blue =    '0x61afef'
  bright.magenta = '0xc678dd'
  bright.cyan =    '0x56b6c2'
  bright.white =   '0xe6efff'

  # Dim colors
  #
  # If the dim colors are not set, they will be calculated automatically based
  # on the `normal` colors.
  dim.black =   '0x1e2127'
  dim.red =     '0xe06c75'
  dim.green =   '0x98c379'
  dim.yellow =  '0xd19a66'
  dim.blue =    '0x61afef'
  dim.magenta = '0xc678dd'
  dim.cyan =    '0x56b6c2'
  dim.white =   '0x828791'

  # Indexed Colors
  #
  # The indexed colors include all colors from 16 to 256.
  # When these are not set, they're filled with sensible defaults.
  #indexed_colors:
  #  - { index: 16, color: '0x000000' }

[bell]
# https://alacritty.org/config-alacritty.html#bell

[selection]
# https://alacritty.org/config-alacritty.html#selection

[cursor]
# https://alacritty.org/config-alacritty.html#cursor

[terminal]
# https://alacritty.org/config-alacritty.html#terminal

[mouse]
# https://alacritty.org/config-alacritty.html#mouse
hide_when_typing = true

[hints]
# https://alacritty.org/config-alacritty.html#hints

[keyboard]
# https://alacritty.org/config-alacritty.html#keyboard
#[[keyboard.bindings]]
#action = "ToggleFullscreen"
#key = "F11"

[debug]
# https://alacritty.org/config-alacritty.html#debug

