# docs: https://alacritty.org/config-alacritty.html
# key bindings: https://alacritty.org/config-alacritty-bindings.html

[general]
# https://alacritty.org/config-alacritty.html#general
live_config_reload = true

[env]
# https://alacritty.org/config-alacritty.html#env
# Add your env vars
# MY_ENV = "value"

[window]
# https://alacritty.org/config-alacritty.html#window
opacity = 0.9
padding.x = 10
padding.y = 10
decorations = "Full"
decorations_theme_variant = "None" # "Dark" | "Light"
dimensions = { columns = 0, lines = 0 }
startup_mode = "Maximized"
option_as_alt = "OnlyLeft" # "OnlyRight" | "Both" | "None"

[font]
# https://alacritty.org/config-alacritty.html#font
size = 15.0
normal.family = "JetBrainsMonoNL Nerd Font Mono"
bold.family = "JetBrainsMonoNL Nerd Font Mono"
italic.family = "JetBrainsMonoNL Nerd Font Mono"
bold_italic.family = "JetBrainsMonoNL Nerd Font Mono"

[scrolling]
# https://alacritty.org/config-alacritty.html#scrolling

[colors]
# https://alacritty.org/config-alacritty.html#colors

[bell]
# https://alacritty.org/config-alacritty.html#bell

[selection]
# https://alacritty.org/config-alacritty.html#selection

[cursor]
# https://alacritty.org/config-alacritty.html#cursor

[terminal]
# https://alacritty.org/config-alacritty.html#terminal

[mouse]
# https://alacritty.org/config-alacritty.html#mouse

[hints]
# https://alacritty.org/config-alacritty.html#hints

[keyboard]
# https://alacritty.org/config-alacritty.html#keyboard

[debug]
# https://alacritty.org/config-alacritty.html#debug

