#!/usr/bin/env bash

# XDG  Base Directory Specification
# - https://specifications.freedesktop.org/basedir-spec/latest/
# - https://wiki.archlinux.org/title/XDG_Base_Directory
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"

# =============================================================================================
#  These are executed only for interactive shells
# =============================================================================================
if [[ -n $PS1 ]]; then
    : # These are executed only for interactive shells


# =============================================================================================
#  These are executed only for NON-interactive shells
# =============================================================================================
else
    : # Only for NON-interactive shells

fi
# =============================================================================================
#  These are executed only when it is a login shell
# =============================================================================================
if shopt -q login_shell ; then
    : # These are executed only when it is a login shell

# =============================================================================================
#  These are executed only when it is NOT a login shell
# =============================================================================================
else
    : # Only when it is NOT a login shell

fi

# =============================================================================================
#  Prompt
# =============================================================================================
PS1="\[${COLOR_GRAY}\]\u@\h:\[${COLOR_GREEN}\]\W\[${COLOR_NC}\] \$ "
# export PS1="\[${COLOR_GREEN}\]\w > \[${COLOR_NC}\]"  # Primary prompt with only a path
# export PS1="\[${COLOR_RED}\]\w > \[${COLOR_NC}\]"  # Primary prompt for root user, to highlight when you're logged in as root
# export PS1="\[${COLOR_GRAY}\]\u@\h \[${COLOR_GREEN}\]\w > \[${COLOR_NC}\]"  # Primary prompt with user, host, and path

# This runs before the prompt and sets the title of the xterm* window.  If you set the title in the prompt
# weird wrapping errors occur on some systems, so this method is superior
# Turn this off of you are running directly in the console on the machine
export PROMPT_COMMAND='echo -ne "\033]0;${USER}@${HOSTNAME%%.*} ${PWD}"; echo -ne "\007"'  # user@host path
export PS2='> '    # Secondary prompt
export PS3='#? '   # Prompt 3
export PS4='+'     # Prompt 4



# Load all files from a $HOME/.shell directory
if [ -d "$HOME/.shell" ]; then
    for file in $HOME/.shell/*
    do
        . $file
    done
fi
